---
title: "p8105_hw6_LC4052"
output: github_document
date: "2025-11-30"
---

```{r}
library(tidyverse)
library(broom)
library(dplyr)
library(ggplot2)
library(modelr)
```


# Problem 1
```{r}
homicide_data = read_csv("./data/homicide-data.csv")
```

```{r}
# Create a new variable
city_state = 
  homicide_data |>
  mutate(
    city_state = str_c(city, ", ", state),
    resolved = as.numeric(disposition == "Closed by arrest")
    ) |>
   filter(
     !city_state %in% c("Tulsa, AL", "Dallas, TX", "Phoenix, AZ", "Kansas City, MO"),
     victim_race %in% c("White", "Black")
     ) |>
  mutate(victim_age = as.numeric(victim_age))
```

```{r}
# Filter out Baltimore
baltimore_data = 
  city_state |>
  filter(city_state == "Baltimore, MD")
```

```{r}
# Fit a logistic regression
btm_glm = 
  baltimore_data |>
  glm(resolved ~ victim_age + victim_sex + victim_race, 
      data = _, 
      family = binomial()) |>
  broom::tidy() 

btm_result = 
  btm_glm |>
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) |>
  filter(term == "victim_sexMale") |>
  select(term, OR, CI_lower, CI_upper)

btm_result
```

```{r}
# Run glm for all cities
city_results = 
  city_state |>
  nest(data = -city_state) |>
  mutate(
    models = map(data, \(df) glm(resolved ~ victim_age + victim_sex + victim_race, data = df, family = binomial())),
  tidy_models = map(models, broom::tidy)
  ) |>
  select(city_state, tidy_models) |>
  unnest(tidy_models) |>
  filter(term == "victim_sexMale") |>
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) |>
  select(city_state, term, OR, CI_lower, CI_upper)

city_results
```

```{r}
# Create a plot
city_results |>
  mutate(city_state = fct_reorder(city_state, OR)) |>
  ggplot(aes(x = OR, y = city_state)) +
  geom_point() +
  geom_errorbarh(aes(xmin = CI_lower, xmax = CI_upper), height = 0.8) +
  geom_vline(xintercept = 1, linetype = "dashed", color = "red") +
  labs(
    title = "Adjusted Odds Ratios for Solving Homicides: Male vs Female Victims",
    x = "Odds Ratio (95% CI)",
    y = NULL
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r}
city_results |>
  summarize(
    cities_below_1 = sum(OR < 1),
    cities_above_1 = sum(OR > 1),
    cities_CI_exclude_1 = sum(CI_upper < 1 | CI_lower > 1)
  )
```
The majority of cities show OR<1, showing that homicides with male victims have lower odds of being solved compared to female victims, after adjusting for victim age, sex and race. Cities such as New York and Baton Rouge have particularly low ORs (< 0.25).

Among all the cities, there are 22 cities whose confidence interval do not include 1.0, suggesting statistically significant differences in solving rates between male and female victim homicides.

Only 6 cities show OR > 1, and these typically have confidence intervals that include 1.0, suggesting no strong evidence that male victim homicides are more likely to be solved.




# Problem 2
```{r}
library(p8105.datasets)
data("weather_df")
set.seed(1)
```

```{r}
# Bootstrap for 5000 times
bootstrap_results = 
  weather_df |>
  modelr::bootstrap(n = 5000) |>
  mutate(
    models = map(strap, \(df) lm(tmax ~ tmin + prcp, data = df)),
    tidy_results = map(models, broom::tidy),
    glance_results = map(models, broom::glance)
  )

bootstrap_results
```

```{r}
# Extract r_squared
r_squared = 
  bootstrap_results |>
  select(glance_results) |>
  unnest(glance_results) |>
  select(r.squared)
```

```{r}
# Extract beta1/beta2
beta_ratio = 
  bootstrap_results |>
  select(tidy_results) |>
  unnest(tidy_results) |>
  select(term, estimate) |>
  pivot_wider(
    names_from = term, 
    values_from = estimate) |>
  unnest(tmin, prcp) |>
  mutate(beta_ratio = tmin/prcp) |>
  select(beta_ratio)

bootstrap_estimates = 
  bind_cols(r_squared, beta_ratio)
```

```{r}
# Estimate of r_squared
r_plot = 
  bootstrap_estimates |>
  ggplot(aes(x = r.squared)) +
  geom_histogram(bins = 50, fill = "steelblue", alpha = 0.7) +
  labs(
    title = "Distribution of Bootstrap R² Estimates",
    x = "R²",
    y = "Frequency"
  ) +
  theme_minimal()

r_plot
```

```{r}
# Estimate of beta_ratio
ratio_plot = 
  bootstrap_estimates |>
  ggplot(aes(x = beta_ratio)) +
  geom_histogram(bins = 50, fill = "steelblue", alpha = 0.7) +
  labs(
    title = "Distribution of Bootstrap β̂₁/β̂₂ Estimates",
    x = "β̂₁/β̂₂ (tmin/prcp)",
    y = "Frequency"
  ) +
  theme_minimal()

ratio_plot
```


```{r}
# 
ci_r_squared = 
  bootstrap_estimates |>
  summarize(
    ci_lower = quantile(r.squared, 0.025),
    ci_upper = quantile(r.squared, 0.975)
  )

ci_beta_ratio = 
  bootstrap_estimates |>
  summarize(
    ci_lower = quantile(beta_ratio, 0.025, na.rm = TRUE),
    ci_upper = quantile(beta_ratio, 0.975, na.rm = TRUE)
  )


ci_r_squared
ci_beta_ratio


bootstrap_estimates |>
  summarize(
    r_squared_mean = mean(r.squared),
    r_squared_sd = sd(r.squared),
    beta_ratio_mean = mean(beta_ratio, na.rm = TRUE),
    beta_ratio_sd = sd(beta_ratio, na.rm = TRUE)
  )

```





NOT DONE: Plot the distribution of your estimates, and describe these in words.




# Problem 3
```{r}
hm_df = 
  read_csv("./data/birthweight.csv") |>
  janitor::clean_names() |>
  mutate(
    babysex = factor(babysex, levels = c(1, 2), 
                     labels = c("Male", "Female")),
    frace   = factor(frace, levels = c(1,2,3,4,8,9),
                     labels = c("White","Black","Asian","Puerto Rican","Other","Unknown")),
    mrace   = factor(mrace, levels = c(1,2,3,4,8),
                     labels = c("White","Black","Asian","Puerto Rican","Other")),
    malform = factor(malform, levels = c(0, 1),
                     labels = c("Absent", "Present"))
  )


summarize(across(everything(), ~sum(is.na(.))))




```

```{r}









```

```{r}














```

```{r}

```

